#!/usr/bin/env bash
export THIS_PATH="$(pwd)"
export BIN_PATH="/usr/bin"

echo "========================"
echo "brut3k1t installer"
echo "========================"

sudo pip2.7 install -r requirements.txt
wget -O driver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
tar -xf driver.tar.gz -C $THIS_PATH
sudo mv geckodriver $BIN_PATH
rm driver.tar.gz

echo "\nDone! Run ./brut3k1t -h to get started!\n"
